version: '3'
services:

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=rsstwopdf_db
      - POSTGRES_USER=rsstwopdf_user
      - POSTGRES_PASSWORD=rsstwopdf_pass
    ports:
      - "5432:5432"
    restart: always
